
services:  
  # PHP Service
  php:
    build: './php_docker/'
    volumes:
      - ./www/:/var/www/html/

  # Apache Service
  apache:
    build: './apache_docker/'
    depends_on:
      - php
    expose:
      - "80" # Solo expuesto al proxy, no al host
    volumes:
      - ./www/:/var/www/html/

  # MariaDB Service
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: password123
    volumes:
      - mysqldata:/var/lib/mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

  # HTTPS Portal (Let's Encrypt)
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "owlstore.zapto.org -> http://apache:80"
      STAGE: "production" # usa "staging" si quieres pruebas sin l√≠mite de Let's Encrypt
    depends_on:
      - apache

# Volumes
volumes:
  mysqldata: